### ISSUE TITLE
Support JPMS

### ISSUE THREAD

**Issue by keilw** [jakartaee/security#184]
While this was optional up to Jakarta EE 9.x with 10 there should be proper JPMS definition, ideally more than just a simple
`Automatic-Module-Name` which Security has not got so far either.

Looking at [JSONB](https://github.com/eclipse-ee4j/jsonb-api/blob/master/api/src/main/java/module-info.java) it also is a good example for inter-dependencies between different specs especially JSON-P in its case.

And since Authorization or Authentication (`<Automatic-Module-Name>jakarta.security.auth.message</Automatic-Module-Name>`) already got at least an `Automatic-Module-Name` with the existing 9.x releases, there should also be something similar between Authentication, Authorization and Security.

**Comment by arjantijms** [comment]
Yes, we should address this. A proper `module-info.java` should be part of the 3.0 release.
