### ISSUE TITLE
Need to triage issues down to what will be addressed for EE10

### ISSUE THREAD

**Issue by starksm64** [jakartaee/security#205]
We have two weeks until the deadline for EE10 individual spec components. We need to triage the current list of issues to what will be addressed for EE10 via an EE10 label and work to create a draft PR by Feb 28.

**Comment by starksm64** [comment]
Hello, the deadline for individual component specifications to create a draft PR in the https://github.com/jakartaee/specifications project with candidate final API and specification is Feb 28. There does not need to be a complete PR with a compatible implementation. All that is required is to have the final candidate API staged, and to have a PR that include the candidate final specification. If your project cannot meet this deadline, it is possible it will miss the EE10 release train. Let the platform dev team(jakartaee-platform-dev@eclipse.org) or the EE10 release coordinator (sstark@redhat.com) when you will be able to create the PR, or if the EE10 platform should release with the previous version.

**Comment by arjantijms** [comment]
Draft PR done: https://github.com/jakartaee/specifications/pull/462
