### ISSUE TITLE
Prepare new Security TCK

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/security#219]
1. [x]  Copying tests to /tck in this project.
2. [x] Changing package names to `ee.jakarta.tck`
3. [ ] Adding (additional) comments to test 
4. [ ] Incorporating the existing TCK from https://github.com/eclipse-ee4j/jakartaee-tck
5. [x] Creating single zip distribution of the entire TCK
6. [ ] Create / update guide / docs on how to run the TCK
5. [ ] Adding example to run TCK as dependency from Maven into your own pom (with other servers, e.g. WildFly)
    (see https://github.com/piranhacloud/piranha/tree/current/external/tck/jwt)
5. [ ] Add signature testing.  There are a few different examples available, one is https://github.com/jakartaee/rest/tree/master/jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/signaturetest + https://github.com/jakartaee/rest/tree/master/jaxrs-tck/src/main/resources/ee/jakarta/tck/ws/rs/signaturetest

**Comment by scottmarlow** [comment]
Please add:
- [ ] Add signature testing.  There are a few different examples available, one is https://github.com/jakartaee/rest/tree/master/jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/signaturetest + https://github.com/jakartaee/rest/tree/master/jaxrs-tck/src/main/resources/ee/jakarta/tck/ws/rs/signaturetest.

**Comment by arjantijms** [comment]
@scottmarlow done, thanks!

**Comment by alwin-joseph** [comment]
> 
>     8. [ ]  Add signature testing.  There are a few different examples available, one is https://github.com/jakartaee/rest/tree/master/jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/signaturetest + https://github.com/jakartaee/rest/tree/master/jaxrs-tck/src/main/resources/ee/jakarta/tck/ws/rs/signaturetest

Created https://github.com/jakartaee/security/pull/226 for this.

**Comment by alwin-joseph** [comment]
> 
>     4. [ ]  Incorporating the existing TCK from https://github.com/eclipse-ee4j/jakartaee-tck
> 
Is it agreeable that we migrate the existing TCK source to this repo, similar to how it was done for faces in https://github.com/jakartaee/faces/pull/1649.

**Comment by scottmarlow** [comment]
> > ```
> > 4. [ ]  Incorporating the existing TCK from https://github.com/eclipse-ee4j/jakartaee-tck
> > ```
> 
> Is it agreeable that we migrate the existing TCK source to this repo, similar to how it was done for faces in [jakartaee/faces#1649](https://github.com/jakartaee/faces/pull/1649).

:+1: 

Note that there were two questions raised I think that might be worth answering:

1.  Are the existing [SecurityAPI tests in the Platform TCK](https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/src/com/sun/ts/tests/securityapi) correctly testing the Security SPEC requirements?  
2.  Are the new SecurityAPI tests already added (and still being updated as needed) to this SPEC API TCK folder correctly testing the Security SPEC requirements?
3. Do we expect to finish the new Security TCK in by the third week of April?  I think this depends on implementations being able to validate that the tests work as expected.  If we don't get that feedback by the third week of April, how does that impact the EE 10 schedule?

**Comment by alwin-joseph** [comment]
@arjantijms @scottmarlow 

I have created https://github.com/jakartaee/security/pull/230 for migrating the old security tck to this repo similar to what was done for faces. Please consider reviewing this.
