### ISSUE TITLE
Finalize the Jakarta Security 3.0 Release

### ISSUE THREAD

**Issue by jeanouii** [jakartaee/security#252]
## Please complete these steps to finalize the release:

- [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
- [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
- [x] if XML Schemas are published on https://jakarta.ee/schemas, send a PR to update the status from Draft to Final.
- [x] approve the compatibility request.
- [x] The compatible implementation project/vendor MUST send an email to [tck@eclipse.org](mailto:tck@eclipse.org) for approval of the compatible implementation for trademark usage.
- [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by arjantijms** [comment]
Email has been send.

**Comment by arjantijms** [comment]
Website has not been updated yet. Will check later again.

**Comment by arjantijms** [comment]
Release 3.0 is in central: https://repo1.maven.org/maven2/jakarta/security/enterprise/jakarta.security.enterprise-api/3.0.0/

**Comment by arjantijms** [comment]
Site is online, and all links are valid. Did do a PR for a minor type and to update the date.

**Comment by arjantijms** [comment]
The release is done, so this can be closed! Thanks to everyone involved!
