### ISSUE TITLE
Security 3.0 is not part of Jakarta EE 10

### ISSUE THREAD

**Issue by hantsy** [jakartaee/security#254]
I have tried to create a Oidc security example, but found I have to add extra security 3.0 API in the dependencies to find the `OpenIdAuthenticationMechanismDefinition`.

Security 3.0 is not part of Jakarta EE 10 final release?

**Comment by arjantijms** [comment]
Security 3.0 is part of the Jakarta EE 10 release. 

See https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee10/JakartaEE10ReleasePlan

**Comment by hantsy** [comment]
Yes, I noticed this.

But in my sample project, https://github.com/hantsy/jakartaee10-sandbox/blob/master/security-oidc/pom.xml

I have added `jakarta.jakartaee-api` 10.0.0, I can not find the `OpenIdAuthenticationMechanismDefinition`, I have to add extra `jakarta.security.enterprise-api` 3.0 to find it.

```xml
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.security.enterprise</groupId>
            <artifactId>jakarta.security.enterprise-api</artifactId>
            <version>3.0.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.glassfish.soteria/jakarta.security.enterprise -->
        <dependency>
            <groupId>org.glassfish.soteria</groupId>
            <artifactId>jakarta.security.enterprise</artifactId>
            <version>3.0.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.glassfish.soteria/soteria.spi.bean.decorator.weld -->
        <dependency>
            <groupId>org.glassfish.soteria</groupId>
            <artifactId>soteria.spi.bean.decorator.weld</artifactId>
            <version>3.0.0</version>
        </dependency>
```

**Comment by arjantijms** [comment]
Jakarta EE 10 (as a full platform) hasn't been officially released, so I guess you're using a staged version. See   https://mvnrepository.com/artifact/jakarta.platform/jakarta.jakartaee-api

Maybe that staged version needs to be updated with the released (final) Security API. Maybe you can file an issue here: https://github.com/eclipse-ee4j/jakartaee-platform

/cc @ivargrimstad

**Comment by hantsy** [comment]
Of course, to experience Jakarta EE 10. 
I added https://jakarta.oss.sonatype.org/content/repositories/staging/ in repositories.

**Comment by hantsy** [comment]
Update the dependency by force, it fixes my issues. Thanks.
