### ISSUE TITLE
typo in authenticationMechanism.adoc

### ISSUE THREAD

**Issue by jimmy1wu** [jakartaee/security#256]
under step 4 of [authentication dialog](https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#authentication-dialog) it says:

```
The ClientSecret value as taken from OpenIdAuthenticationMechanismDefinition.clientId
```

should be:

```
The ClientSecret value as taken from OpenIdAuthenticationMechanismDefinition.clientSecret
```

**Comment by arjantijms** [comment]
Thanks for the mention. If you want you can do a PR to change it so you get the credit. Otherwise I'll update it. Thanks again!

**Comment by jimmy1wu** [comment]
@arjantijms 

i have created a pr to fix this typo
PTAL https://github.com/jakartaee/security/pull/257 🙂
