### ISSUE TITLE
[TCK Challenge] Ignore ee.jakarta.tck.security.test.AppMemBasicDecorateIT.testNotAuthenticatedAndDecorated()

### ISSUE THREAD

**Issue by darranl** [jakartaee/security#270]
Following on the discussions under the issue https://github.com/jakartaee/security/issues/267 and related approved PR https://github.com/jakartaee/security/pull/268 I am raising this challenge to request the ability to ignore the results of the following test whilst using version 3.0.0 of the Jakarta Security TCK:

ee.jakarta.tck.security.test.AppMemBasicDecorateIT.testNotAuthenticatedAndDecorated()

**Comment by fjuma** [comment]
This challenge should also include `ee.jakarta.tck.security.test.AppMemBasicDecorateIT.testAuthenticated()`. This test fails for the same reason as `ee.jakarta.tck.security.test.AppMemBasicDecorateIT.testNotAuthenticatedAndDecorated()`.

**Comment by bstansberry** [comment]
Please find attached the failure details from the app-mem-basic-decorate module run against current WildFly main:

[Issue_270_details.zip](https://github.com/jakartaee/security/files/9445836/Issue_270_details.zip)

**Comment by arjantijms** [comment]
It's somewhat controversial whether the code that the test uses internally is actually illegal, but since its an internal detail and totally not relevant to what the test is actually testing the test has indeed been adjusted.

Since the ability to decorate is rather important and we have no other test coverage for this, I'd like to propose asking for an exception first to include the updated test in a revision of the TCK.

Thoughts?

**Comment by bstansberry** [comment]
It depends on timing. We are close to being able to send up CCRs, so we filed this challenge to avoid blocking that.

The EE 10 Full Platform and Web Profile ballots have started so the urgency of WildFly trying to file CCRs before that happened is gone. So a delay of a couple days should be fine, but if it's going to take a while and this becomes the only blocking issue I'd like to see this accepted.

**Comment by arjantijms** [comment]
@bstansberry good point, I see the concern.

I'll bring it up in the platform meeting today, and see if a vote can be organised in a couple of days. If not I'll accept the challenge and then the test will very likely be part of at least EE 11 again.

**Comment by brideck** [comment]
This challenge impacts Open Liberty, so we are also eager to see a resolution here.

**Comment by teddyjtorres** [comment]
Hi @arjantijms,
Please let us know if this challenge has been accepted or if more information is needed.

Regards,
Teddy

**Comment by arjantijms** [comment]
We had apparently forgotten to merge this back in August / September, but it's merged now. This should conclude the challenge.
