### ISSUE TITLE
Clarify @RolesAllowed and authorization modules enhancements

### ISSUE THREAD

**Issue by ayoho** [jakartaee/security#294]
The [Security 4.0 release plan](https://jakarta.ee/specifications/security/4.0/) mentions two points that don't have further details:
- @RolesAllowed alternative
- Authorization modules

Scott Stark [brought this up in the mailing list in July](https://www.eclipse.org/lists/jakarta.ee-spec/msg03015.html) with [Arjan providing some links to related questions](https://www.eclipse.org/lists/jakarta.ee-spec/msg03018.html):
- https://github.com/jakartaee/security/issues/204
- https://stackoverflow.com/questions/27341665/is-it-possible-to-determine-group-membership-of-a-user-on-demand-instead-of-when
- https://arjan-tijms.omnifaces.org/2016/07/simplified-custom-authorization-rules.html

However there still needs to be some specifics provided about what exactly is planned to be enhanced in Security 4.0.

**Comment by arjantijms** [comment]
See https://github.com/jakartaee/security/issues/296 and https://github.com/jakartaee/security/issues/295
