### ISSUE TITLE
Allow qualifiers to be specified for the build-in authentication mechanisms

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/security#311]
Jakarta Security provides a number of build-in authentication mechanisms. These are enabled via a ...Definition annotation which adds a `Bean<T>` to CDI's beans with among its types `HttpAuthenticationMechanism`. We don't know the actual type of it, as that is implementation specific.

In the case that we enable multiple authentication mechanisms, we can't see which one was created via which ...Definition annotation. I.e. we don't know if it's a basic authentication mechanism or a form one, etc.

To solve that problem, we should introduce qualifiers for the ...Definition annotation. Via such qualifier we can inject and/or introspect beans.

**Comment by OndroMih** [comment]
I believe this, together with https://github.com/jakartaee/security/issues/309, would more or less resolve https://github.com/jakartaee/security/issues/188.
