### ISSUE TITLE
Compatibility certification request for Soteria 4.0.0

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/security#338]
- [x] Organization Name ("Organization") and, if applicable, URL
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)
  [Soteria 4.0.0](https://github.com/eclipse-ee4j/soteria/releases/tag/4.0.0-RELEASE)
  [Eclipse Glassfish 8.0.0-M6](https://repo1.maven.org/maven2/org/glassfish/main/distributions/glassfish/8.0.0-M6/glassfish-8.0.0-M6.zip) (JDK 21)
   [Eclipse Glassfish 8.0.0-JDK-17-M6](https://repo1.maven.org/maven2/org/glassfish/main/distributions/glassfish/8.0.0-JDK17-M6/) (JDK 17)
- [x] Specification Name, Version and download URL
  [Jakarta Security, 4.0](https://jakarta.ee/specifications/security/4.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL
  [Jakarta Security TCK 4.0](https://www.eclipse.org/downloads/download.php?file=/security/jakartaee11/staged/eftl/jakarta-security-tck-4.0.0.zip), SHA-256: `e21a3d8251bf954c99a3f9a5f71911696509a1ed40c23673760785a3b88e4172`
- [x] Public URL of TCK Results Summary
  https://github.com/eclipse-ee4j/soteria/wiki/Jakarta-Security-4.0-TCK-Soteria-Results
- [x] Any Additional Specification Certification Requirements
  None
- [x] Java runtime used to run the implementation
  openjdk version "21.0.2" 2024-01-16 OpenJDK Runtime Environment (build 21.0.2+13-58) OpenJDK 64-Bit Server VM (build 21.0.2+13-58, mixed mode, sharing)
  openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment (build 17.0.2+8-86) OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
- [x] Summary of the information for the certification environment, operating system, cloud, ...
  Debian GNU/Linux 10 (buster)
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by jeanouii** [comment]
Hey Arjan, you can probably check the public URL for the TCK results. You added the link and I checked it just now

**Comment by arjantijms** [comment]
> Hey Arjan, you can probably check the public URL for the TCK results. You added the link and I checked it just now

Done, thanks! :)

**Comment by arjantijms** [comment]
As the project lead of Jakarta Security and Eclipse Soteria, I assert this is complete and can be accepted.
