### ISSUE TITLE
Finalize the Security 4.0 Release

### ISSUE THREAD

**Issue by ivargrimstad** [jakartaee/security#339]
Please complete these steps to finalize the release
- [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] n/a  if XML Schemas are published on https://jakarta.ee/schemas, send a PR to update the status from `Draft` to `Final`.
 - [x] approve the compatibility request.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by arjantijms** [comment]
All steps have been completed
